name: Build & Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./FourTwenty.LokoMerchant.Client/FourTwenty.LokoMerchant.Client.sln

      - name: Build
        run: dotnet build ./FourTwenty.LokoMerchant.Client/FourTwenty.LokoMerchant.Client.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test ./FourTwenty.LokoMerchant.Client/FourTwenty.LokoMerchant.Client.sln --no-build --configuration Release --verbosity normal
