name: Release & Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./FourTwenty.LokoMerchant.Client/FourTwenty.LokoMerchant.Client.sln

      - name: Extract version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build
        run: dotnet build ./FourTwenty.LokoMerchant.Client/FourTwenty.LokoMerchant.Client.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test ./FourTwenty.LokoMerchant.Client/FourTwenty.LokoMerchant.Client.sln --no-build --configuration Release --verbosity normal

      - name: Pack
        run: dotnet pack ./FourTwenty.LokoMerchant.Client/FourTwenty.LokoMerchant.Client/FourTwenty.LokoMerchant.Client.csproj --no-build --configuration Release --output ./nupkg -p:Version=${{ steps.get_version.outputs.version }}

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./nupkg/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
